# Generated by Django 4.0.3 on 2023-08-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'blog_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataEngCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('avg_size', models.FloatField(blank=True, null=True)),
                ('avg_cost', models.FloatField(blank=True, null=True)),
                ('place_code', models.IntegerField(blank=True, null=True)),
                ('op_ratio', models.IntegerField(blank=True, null=True)),
                ('total_deal', models.IntegerField(blank=True, null=True)),
                ('month_fee_ratio', models.IntegerField(blank=True, null=True)),
                ('new_ratio', models.IntegerField(blank=True, null=True)),
                ('bus_stop', models.IntegerField(blank=True, null=True)),
                ('art', models.IntegerField(blank=True, null=True)),
                ('bike', models.IntegerField(blank=True, null=True)),
                ('gym', models.IntegerField(blank=True, null=True)),
                ('chatolic', models.IntegerField(blank=True, null=True)),
                ('hospital', models.IntegerField(blank=True, null=True)),
                ('perform_place', models.IntegerField(blank=True, null=True)),
                ('park', models.IntegerField(blank=True, null=True)),
                ('theater', models.IntegerField(blank=True, null=True)),
                ('subway', models.IntegerField(blank=True, null=True)),
                ('animal_hospital', models.IntegerField(blank=True, null=True)),
                ('beatuy_care', models.IntegerField(blank=True, null=True)),
                ('coin_karaoke', models.IntegerField(blank=True, null=True)),
                ('liberary', models.IntegerField(blank=True, null=True)),
                ('church', models.IntegerField(blank=True, null=True)),
                ('big_mart', models.IntegerField(blank=True, null=True)),
                ('gonggogng_gym', models.IntegerField(blank=True, null=True)),
                ('caf챕', models.IntegerField(blank=True, null=True)),
                ('police_office', models.IntegerField(blank=True, null=True)),
                ('daiso', models.IntegerField(blank=True, null=True)),
                ('bar', models.IntegerField(blank=True, null=True)),
                ('shopping_center', models.IntegerField(blank=True, null=True)),
                ('super_market', models.IntegerField(blank=True, null=True)),
                ('pharmacy', models.IntegerField(blank=True, null=True)),
                ('banchan', models.IntegerField(blank=True, null=True)),
                ('convience_store', models.IntegerField(blank=True, null=True)),
                ('bank', models.IntegerField(blank=True, null=True)),
                ('coin_wash_room', models.IntegerField(blank=True, null=True)),
                ('yoga', models.IntegerField(blank=True, null=True)),
                ('cross_fit', models.IntegerField(blank=True, null=True)),
                ('atm', models.IntegerField(blank=True, db_column='ATM', null=True)),
                ('food_store', models.IntegerField(blank=True, null=True)),
                ('post_office', models.IntegerField(blank=True, null=True)),
                ('pc_room', models.IntegerField(blank=True, db_column='PC_room', null=True)),
                ('piilates', models.IntegerField(blank=True, null=True)),
                ('citizen_center', models.IntegerField(blank=True, null=True)),
                ('temple', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_eng_csv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
